### PR TITLE
Use gcompris-qt where gcompris command line option is unavailable.

### PR DESCRIPTION
**Pull request by chimosky**
@quozl kindly review.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Why is this needed?  What caused it?  Would it be better to check for the file rather than use an exception handler?  The exception OSError is a bit vague.

**Comment by chimosky** [comment]
> Thanks. Why is this needed? What caused it? Would it be better to check for the file rather than use an exception handler? The exception OSError is a bit vague.

It's needed because `gcompris` command line option is `gcompris-qt` in some systems - debian to be precise -. We can check for the file but the location in the live build is quite different - `/usr/games/gcompris-qt`. 
The exception is thrown by `subprocess.Popen` when it can't find the file, the exception handler is for the case where it's installed as `gcompris-qt`.

**Comment by chimosky** [comment]
Error thrown
```
Traceback (most recent call last):
  File "/usr/local/bin/sugar-activity", line 5, in <module>
    activityinstance.main()
  File "/usr/local/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 230, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/local/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
  File "/home/ibiam/Activities/gcompris-wrapper-activity/activity.py", line 40, in __init__
    proc = subprocess.Popen(options)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Caused by running `gcompris` when it's not installed or installed under a different name.

**Comment by quozl** [comment]
How about check for OSError with Errno 2, and if not 2 then raise the exception again.

**Comment by chimosky** [comment]
> How about check for OSError with Errno 2, and if not 2 then raise the exception again.

I don't understand.

**Comment by quozl** [comment]
Your traceback and error shows [Errno 2], which is _errno.ENOENT_;

```log
>>> import errno
>>> errno.errorcode(2)
'ENOENT'
>>>
```

You can reuse a technique in [SafeLogWrapper](https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/b6e314bbe58d11b223a8b152b1240649aa203dce/src/sugar3/logger.py#L139) where an exception handler is declared surrounding the call to _write_, which catches _IOError_ and checks the _errno_ attribute against a known cause _ENOSPC_ (No space left on device).  The only purpose is to suppress the exception when disk is full.

So to avoid the vague handling of every _OSError_, you could check for _errno.ENOENT_ (No such file or directory) and `raise` the exception if it isn't _ENOENT_.

Interactive test on Python 2:

```log
>>> import errno
>>> import subprocess
>>> try:
...     proc = subprocess.Popen(['/tmp/missingfile'])
... except OSError as e:
...     if e.errno != errno.ENOENT:
...         raise e
...     print e.errno
... 
2
>>> 
```

Because there can be other reasons for _Popen_ to fail.

On Python 3 you can instead handle _FileNotFoundError_.

```log
>>> import subprocess
>>> try:
...     proc = subprocess.Popen(['/tmp/missingfile'])
... except FileNotFoundError:
...     pass
```

**Comment by chimosky** [comment]
I understand now, thanks.

**Comment by chimosky** [comment]
> On Python 3 you can instead handle FileNotFoundError.

Handling a `FileNotFoundError` raises a `NameError: global name 'FileNotFoundError' is not defined` error, so I handled `OSError` as that's what was raised.
@quozl kindly review.

**Comment by quozl** [comment]
Yeah, that only works on Python 3.

**Pull request merged**
